#!/usr/bin/env python

import argparse

verbose = False

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='A python template.', 
                        epilog='Additional information.')
    parser.add_argument('-v', '--verbose', help='be verbose', 
                        action='store_true') 
    parser.add_argument('vars', nargs='*')
    args = parser.parse_args()

    verbose = args.verbose
